[package]
name = "optionstratlib"
version = "0.3.2"
edition = "2021"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionStratLib is a comprehensive Rust library for options trading and strategy development across multiple asset classes."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionStratLib"
homepage = "https://github.com/joaquinbejar/OptionStratLib"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]


include = [
    "benches/**/*",
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "examples/**/*.rs",
    "tests/**/*.rs",
    "Makefile",
    "rust-toolchain.toml",
    "Draws/**/*.png",
    "Docker/**/*.Dockerfile",
    "Docker/**/*.yml",
]

[dependencies]
chrono = { version = ">=0.4.39", features = ["wasmbind"] }
approx = "0.5.1"
plotters = { version = "0.3.7" }
plotters-canvas = "0.3"
web-sys = { version = "0.3", features = ["HtmlCanvasElement"], optional = true }
statrs = "0.18.0"
rand = { version = "0.8.5", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", optional = true }
num-traits = "0.2.19"
serde_json = "1.0.135"
csv = { version = "1.3.1", optional = true }
serde = { version = "1.0.217", features = ["derive"] }
rayon = { version = "1.10.0" }
itertools = "0.14.0"
rust_decimal = { version = "1.36.0", features = ["maths", "serde"] }
rust_decimal_macros = "1.36.0"

[dev-dependencies]
criterion = { version = "0.5.1", default-features = false, features = ["html_reports"] }
wasm-bindgen = { version = "0.2" }
wasm-bindgen-test = { version = "0.3.34" }

[[test]]
name = "tests"
path = "tests/unit/mod.rs"

[[bench]]
name = "benches"
path = "benches/mod.rs"
harness = false

[lib]
name = "optionstratlib"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[workspace]
members = [
    "examples/examples_simulation",
    "examples/examples_strategies_best",
    "examples/examples_strategies_delta",
    "examples/examples_strategies",
    "examples/examples_visualization",
    "examples/examples_chain",
    "examples/examples_volatility",
    "examples/examples_curves",
]

[workspace.dependencies]
optionstratlib = { path = "." }
tracing = "0.1.41"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csv = "1.3.1"
tracing-subscriber = "0.3.19"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.98"
console_error_panic_hook = "0.1.7"
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }
wasm-bindgen-test = "0.3"
chrono = { version = ">=0.4.39", features = ["wasmbind"] }
wasm-bindgen-rayon = "1.3"

# [features]
# default = ["native"]
# native = ["rayon", "csv", "tracing-subscriber"]
# wasm = ["wasm-bindgen", "chrono/wasmbind", "web-sys"]
