[package]
name = "optionstratlib"
version = "0.2.1"
edition = "2021"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionStratLib is a comprehensive Rust library for options trading and strategy development across multiple asset classes."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionStratLib"
homepage = "https://github.com/joaquinbejar/OptionStratLib"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]

include = [
    "src/**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "examples/**/*.rs",
    "tests/**/*.rs",
    "Makefile",
    "rust-toolchain.toml",
    "Draws/**/*.png",
    "Docker/**/*.Dockerfile",
    "Docker/**/*.yml",
]

[dependencies]
chrono = "0.4.38"
approx = "0.5.1"
plotters = "0.3.7"
statrs = "0.17.1"
rand = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
num-traits = "0.2.14"
serde_json = "1.0.128"
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
rayon = "1.10.0"


[dev-dependencies]
assert-json-diff = "2.0.2"
mockall = "0.13.0"
tokio-test = "0.4.4"
futures-util = "0.3.30"
async-std = "1.12.0"
lazy_static = "1.5.0"

[[test]]
name = "tests"
path = "tests/unit/mod.rs"

[lib]
name = "optionstratlib"
path = "src/lib.rs"

