[package]
name = "optionstratlib"
version = "0.3.2"
edition = "2021"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionStratLib is a comprehensive Rust library for options trading and strategy development across multiple asset classes."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionStratLib"
homepage = "https://github.com/joaquinbejar/OptionStratLib"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]


include = [
    "benches/**/*",
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "examples/**/*.rs",
    "tests/**/*.rs",
    "Makefile",
    "rust-toolchain.toml",
    "Draws/**/*.png",
    "Docker/**/*.Dockerfile",
    "Docker/**/*.yml",
]

[dependencies]
chrono = ">=0.4.39"
approx = "0.5.1"
plotters = "0.3.7"
statrs = "0.18.0"
rand = "0.8.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
num-traits = "0.2.19"
serde_json = "1.0.135"
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
rayon = "1.10.0"
itertools = "0.14.0"
rust_decimal = { version = "1.36.0", features = ["maths", "serde"] }
rust_decimal_macros = "1.36.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[test]]
name = "tests"
path = "tests/unit/mod.rs"

[[bench]]
name = "benches"
path = "benches/mod.rs"
harness = false

[lib]
name = "optionstratlib"
path = "src/lib.rs"

[workspace]
members = [
    "examples/examples_simulation",
    "examples/examples_strategies_best",
    "examples/examples_strategies_delta",
    "examples/examples_strategies",
    "examples/examples_visualization",
    "examples/examples_chain",
    "examples/examples_volatility",
    "examples/examples_curves",
]

[workspace.dependencies]
optionstratlib = { path = "." }
tracing = "0.1.41"
