[package]
name = "optionstratlib"
version = "0.2.3"
edition = "2021"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionStratLib is a comprehensive Rust library for options trading and strategy development across multiple asset classes."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionStratLib"
homepage = "https://github.com/joaquinbejar/OptionStratLib"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]


include = [
    "src/**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "examples/**/*.rs",
    "tests/**/*.rs",
    "Makefile",
    "rust-toolchain.toml",
    "Draws/**/*.png",
    "Docker/**/*.Dockerfile",
    "Docker/**/*.yml",
]

[dependencies]
chrono = "0.4.38"
approx = "0.5.1"
plotters = "0.3.7"
statrs = "0.17.1"
rand = "0.8.5"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
num-traits = "0.2.19"
serde_json = "1.0.133"
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
rayon = "1.10.0"
itertools = "0.13.0"

[[test]]
name = "tests"
path = "tests/unit/mod.rs"

[lib]
name = "optionstratlib"
path = "src/lib.rs"

[workspace]
members = [
    "examples/examples_simulation",
    "examples/examples_strategies_best",
    "examples/examples_strategies",
    "examples/examples_visualization",
    "examples/examples_chain",
    "examples/examples_volatility",
]

[workspace.dependencies]
optionstratlib = { path = "." }
tracing = "0.1.41"
