[package]
name = "optionstratlib"
version = "0.1.0"
edition = "2021"
authors = ["Joaquin Bejar <jb@taunais.com>"]
description = "OptionStratLib is a comprehensive Rust library for options trading and strategy development across multiple asset classes."
license = "MIT"
readme = "README.md"
repository = "https://github.com/joaquinbejar/OptionStratLib"
homepage = "https://github.com/joaquinbejar/OptionStratLib"
keywords = ["finance", "options", "trading"]
categories = ["finance", "data-structures"]
exclude = [
    "/examples",
    "/tests",
    "/target",
    "/.git",
    "/.github",
    "/.idea",
    "/.vscode",
    "Cargo.lock",
    "/**/.DS_Store",
]
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE",
    "examples/**/*",
    "tests/**/*",
    "Makefile",
    "rust-toolchain.toml",
    "Draws/**/*",
    "Docker/**/*",
]

[dependencies]
chrono = "0.4.38"
approx = "0.5.1"
plotters = "0.3.7"
statrs = "0.17.1"
rayon = "1.10.0"
rand = "0.8.5"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
assert-json-diff = "2.0.2"
mockall = "0.13.0"
tokio-test = "0.4.4"
futures-util = "0.3.30"
async-std = "1.12.0"
lazy_static = "1.5.0"


[[example]]
name = "example"
path = "examples/volatility.rs"

[[test]]
name = "tests"
path = "tests/unit/mod.rs"

[lib]
name = "optionstratlib"
path = "src/lib.rs"

