[package]
name = "examples_strategies_delta"
version = "0.1.0"
edition = "2024"

[dependencies]
optionstratlib = { workspace = true }
tracing = { workspace = true }
rust_decimal_macros = { workspace = true }
rust_decimal = { workspace = true }