[package]
name = "examples_volatility"
version = "0.1.0"
edition = "2021"

[dependencies]
optionstratlib = { path = "../.." }
tracing = "0.1.41"
statrs = "0.17.1"
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"