name: Build WASM Target
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install WASM tool chain
        run: rustup +nightly target add wasm32-unknown-unknown

      - name: Check WASM Target Compiles
        run: make wasm-build
