name: Build

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, archlinux, macos-latest]
    
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies (make)
        if: runner.os != 'Linux'
        run: |
          if [ "${{ matrix.os }}" = "archlinux" ]; then
            sudo pacman -Syu --noconfirm make
          else
            sudo apt-get update
            sudo apt-get install -y make
          fi

      - name: Build
        run: make build