name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    
    - name: Install make
      run: sudo apt-get install make
    
    - name: Build
      run: make build
    
    - name: Format check
      run: make fmt
    
    - name: Lint
      run: make lint
    
    - name: Run tests
      run: make test

    - name: Generate code coverage report
      run: make coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./lcov.info
        fail_ci_if_error: true