name: SEMVER

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - 'release/**'

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: full

jobs:
  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          package: optionstratlib
          feature-group: all-features
          rust-toolchain: stable
          release-type: minor
