name: Run WASM Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
          components: rust-src

      - name: Install dependencies
        run: |
          if [ "${{ matrix.container }}" = "archlinux:latest" ]; then
            pacman -Syu --noconfirm make fontconfig pkgconf
          elif [ "${{ runner.os }}" = "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y make libfontconfig1-dev pkg-config
          elif [ "${{ runner.os }}" = "macOS" ]; then
            brew install make fontconfig pkg-config
          fi

      - name: Install wasm-bindgen to run tests
        run: cargo install wasm-bindgen-cli

      - name: Run WASM tests
        run: make wasm-test
