name: Run WASM Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

env:
  CARGO_TERM_COLOR: always

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Install WASM tool chain
        run: rustup +nightly target add wasm32-unknown-unknown

      - name: Run WASM tests
        run: make wasm-test
